"""
Regression tests for the pluggable selection strategies (JBCS revision, Task 2).

The critical guarantee: the `longest` strategy must reproduce the
pre-revision published behavior byte-for-byte (the committed
outputs/taeg_summary_lexrank-ta.txt was generated by the original
max(key=len) implementation).
"""

import sys
import os
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))
sys.path.insert(0, str(REPO_ROOT))

from selection_strategies import (  # noqa: E402
    GOSPEL_ORDER,
    CentroidStrategy,
    LongestStrategy,
    PriorityStrategy,
    RandomStrategy,
    get_strategy,
)


@pytest.fixture(scope="session", autouse=True)
def repo_cwd():
    """Data paths are relative to the repo root."""
    old = os.getcwd()
    os.chdir(REPO_ROOT)
    yield
    os.chdir(old)


@pytest.fixture(scope="session")
def graph():
    from improved_graph_builder import ImprovedTemporalGraphBuilder
    return ImprovedTemporalGraphBuilder().build_improved_temporal_graph(verbose=False)


@pytest.fixture(scope="session")
def consolidator():
    from summarizer import LexRankTemporalAnchoring
    return LexRankTemporalAnchoring()


def test_longest_is_byte_identical_to_published_output(consolidator, graph):
    """The refactored loop + longest strategy must regenerate the committed
    pre-revision summary exactly."""
    committed = (REPO_ROOT / "outputs" / "taeg_summary_lexrank-ta.txt").read_text(encoding="utf-8")
    summary, records = consolidator.consolidate_with_strategy(
        LongestStrategy(), graph=graph, verbose=False)
    assert summary == committed
    assert len(records) == 169


def test_longest_matches_legacy_max_len_rule(consolidator, graph):
    _, records = consolidator.consolidate_with_strategy(
        LongestStrategy(), graph=graph, verbose=False)
    for rec in records:
        if rec["fallback"]:
            continue
        max_len = max(c["text_length"] for c in rec["candidates"])
        chosen = next(c for c in rec["candidates"] if c["node_id"] == rec["chosen_node"])
        assert chosen["text_length"] == max_len


def test_priority_picks_highest_priority_available(consolidator, graph):
    _, records = consolidator.consolidate_with_strategy(
        PriorityStrategy(), graph=graph, verbose=False)
    for rec in records:
        if rec["fallback"]:
            continue
        available = [c["gospel"] for c in rec["candidates"]]
        expected = min(available, key=GOSPEL_ORDER.index)
        assert rec["chosen_gospel"] == expected


def test_random_is_seed_reproducible_and_valid(consolidator, graph):
    s1, r1 = consolidator.consolidate_with_strategy(
        RandomStrategy(seed=42), graph=graph, verbose=False)
    s2, r2 = consolidator.consolidate_with_strategy(
        RandomStrategy(seed=42), graph=graph, verbose=False)
    s3, _ = consolidator.consolidate_with_strategy(
        RandomStrategy(seed=7), graph=graph, verbose=False)
    assert s1 == s2
    assert s1 != s3  # 96 contested events: collision is virtually impossible
    for rec in r1:
        if not rec["fallback"]:
            assert rec["chosen_node"] in {c["node_id"] for c in rec["candidates"]}


def test_centroid_is_deterministic_and_ties_break_canonically(consolidator, graph):
    s1, r1 = consolidator.consolidate_with_strategy(
        CentroidStrategy(), graph=graph, verbose=False)
    s2, _ = consolidator.consolidate_with_strategy(
        CentroidStrategy(), graph=graph, verbose=False)
    assert s1 == s2
    for rec in r1:
        if rec["fallback"] or rec["n_candidates"] != 2:
            continue
        # With two versions the mean cosine to "the others" is symmetric,
        # so the tie must resolve to the earliest gospel in canonical order.
        gospels = [c["gospel"] for c in rec["candidates"]]
        assert rec["chosen_gospel"] == min(gospels, key=GOSPEL_ORDER.index)


def test_every_strategy_shares_the_same_timeline_skeleton(consolidator, graph):
    """All strategies must emit one record per canonical event, with identical
    fallback events — only the chosen version may differ."""
    strategies = [LongestStrategy(), PriorityStrategy(), CentroidStrategy(),
                  RandomStrategy(seed=0)]
    all_records = [consolidator.consolidate_with_strategy(s, graph=graph, verbose=False)[1]
                   for s in strategies]
    for records in all_records[1:]:
        assert [r["event_id"] for r in records] == [r["event_id"] for r in all_records[0]]
        assert [r["fallback"] for r in records] == [r["fallback"] for r in all_records[0]]


def test_get_strategy_registry():
    assert isinstance(get_strategy("longest"), LongestStrategy)
    assert isinstance(get_strategy("random", seed=1), RandomStrategy)
    assert isinstance(get_strategy("priority"), PriorityStrategy)
    assert isinstance(get_strategy("centroid"), CentroidStrategy)
    with pytest.raises(ValueError):
        get_strategy("random")  # seed required
    with pytest.raises(ValueError):
        get_strategy("taeg")  # centrality required
    with pytest.raises(ValueError):
        get_strategy("nope")
